apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
spec:
  project: development
  source:
    repoURL: https://github.com/wonderfulmaxx/mwinter-IOT
    targetRevision: HEAD
    path: .
  destination:
    server : https://kubernetes.default.svc
    namespace: dev  
syncPolicy:
    automated:
      prune: true
      selfHeal: true
